select 
    ad_id,
    add_to_cart,
    adset_id,
    campaign_id,
    'Facebook' as channel,
    clicks,
    comments,
    creative_id,
    date,
    likes + shares + clicks + comments + views as engagements,
    impressions,
    mobile_app_install as installs,
    likes,
    null as link_clicks,
    null as placement_id,
    null as post_click_conversions,
    null as post_view_conversions,
    null as posts,
    purchase,
    complete_registration as registrations,
    purchase_value as revenue,
    shares,
    spend,
    purchase as total_conversions,
    null as video_views

from {{ ref('src_ads_creative_facebook_all_data') }}